### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by chrdavis** [luketimothyjones/pynetcheck#5]
Hit this on the second run of the speed test
Running pings...Traceback (most recent call last):
  File "c:\pynetcheck\netcheck.py", line 152, in <module>
    main()
  File "c:\pynetcheck\netcheck.py", line 146, in main
    ping_speedtest_save()
  File "c:\pynetcheck\netcheck.py", line 91, in ping_speedtest_save
    min_ms = min_ms_re.search(data).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by samipfjo** [comment]
Operating system?

**Comment by chrdavis** [comment]
Windows 10.  I called out the fix in the PR that is open.  Issues with my router resulted in pings all of a sudden failing 100% so the regular expression wasn't matching anything.  Fix is easy.

You can reproduce it by pinging test.com instead.  It won't reply to pings.
